#pragma once

// Every public type in sq::gui.
// Prefer a narrower include in headers of your own.

#include <squared/gui/alignment.hpp>
#include <squared/gui/button.hpp>
#include <squared/gui/button_group.hpp>
#include <squared/gui/button_style.hpp>
#include <squared/gui/cell.hpp>
#include <squared/gui/check_box.hpp>
#include <squared/gui/check_box_style.hpp>
#include <squared/gui/color_drawable.hpp>
#include <squared/gui/dialog.hpp>
#include <squared/gui/direction.hpp>
#include <squared/gui/drawable.hpp>
#include <squared/gui/drawable_ptr.hpp>
#include <squared/gui/font_ptr.hpp>
#include <squared/gui/font_resource.hpp>
#include <squared/gui/image.hpp>
#include <squared/gui/insets.hpp>
#include <squared/gui/key.hpp>
#include <squared/gui/key_modifiers.hpp>
#include <squared/gui/label.hpp>
#include <squared/gui/label_style.hpp>
#include <squared/gui/linear_layout.hpp>
#include <squared/gui/margin_container.hpp>
#include <squared/gui/nine_patch_drawable.hpp>
#include <squared/gui/nine_patch_splits.hpp>
#include <squared/gui/painter.hpp>
#include <squared/gui/panel.hpp>
#include <squared/gui/panel_style.hpp>
#include <squared/gui/pointer_action.hpp>
#include <squared/gui/pointer_event.hpp>
#include <squared/gui/progress_bar.hpp>
#include <squared/gui/progress_bar_style.hpp>
#include <squared/gui/radio_button.hpp>
#include <squared/gui/rectangle.hpp>
#include <squared/gui/region_drawable.hpp>
#include <squared/gui/scroll_pane.hpp>
#include <squared/gui/separator.hpp>
#include <squared/gui/size.hpp>
#include <squared/gui/size_hints.hpp>
#include <squared/gui/skin.hpp>
#include <squared/gui/skin_drawable_resolver.hpp>
#include <squared/gui/skin_font_resolver.hpp>
#include <squared/gui/skin_load_issue.hpp>
#include <squared/gui/skin_load_limits.hpp>
#include <squared/gui/skin_load_report.hpp>
#include <squared/gui/skin_load_severity.hpp>
#include <squared/gui/slider.hpp>
#include <squared/gui/slider_style.hpp>
#include <squared/gui/stack.hpp>
#include <squared/gui/table.hpp>
#include <squared/gui/text_field.hpp>
#include <squared/gui/text_field_style.hpp>
#include <squared/gui/toggle_button.hpp>
#include <squared/gui/tooltip_config.hpp>
#include <squared/gui/ui.hpp>
#include <squared/gui/widget.hpp>
#include <squared/gui/window.hpp>
#include <squared/gui/window_style.hpp>
